# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='widgets',
            field=models.ManyToManyField(related_name='containing_dashboards', through='widget.WidgetConfig', to='widget.Widget'),
        ),
    ]
