# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 22:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Widget', max_length=32)),
                ('width', models.IntegerField(default=2)),
                ('height', models.IntegerField(default=2)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
