# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('querystring_key', models.CharField(max_length=64)),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('default_value', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('author', models.TextField(max_length=20, null=True)),
                ('widgettype', models.CharField(blank=True, max_length=64, null=True)),
                ('width', models.IntegerField(default=2)),
                ('height', models.IntegerField(default=2)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('showbutton', models.BooleanField(default=False)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('facetdash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
                ('parameters', models.ManyToManyField(to='widget.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widget.Widget')),
            ],
        ),
    ]
