# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='author',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
